Fix Exception nach #3150: Dialog Karte mit Adressfeld besser abstimmen
bfpi/klarschiff-backoffice pull request #133
Opened 2022-01-21 06:23 UTC by ro3t

2022-01-21 06:37 UTC, nbennke requested changes

2022-01-21 06:37 UTC, nbennke commented on app/assets/javascripts/maps.coffee.erb
> +    method: 'GET'
Warum hier der Wechsel auf `GET`? Für Updates ist doch `PUT`/`PATCH` vorgesehen.

2022-01-21 07:00 UTC, ro3t commented on app/assets/javascripts/maps.coffee.erb
> +    method: 'GET'
Ist wieder auf PUT

2022-01-21 08:43 UTC, nbennke requested changes
Da inhaltlich entsteht gar keine direkte Änderung an einer Meldung erfolgt, ist es doch `GET` Content, jedoch nicht gegen den `IssuesController`.

Bitte die Action als `resource :place, only: :show` bereit stellen und dann auf `data-place-url: place_path` umstellen.

2022-01-25 19:17 UTC, nbennke approved these changes

2022-01-25 19:17 UTC, merged