Ticket 2713
bfpi/klarschiff-backoffice pull request #14
Opened 2021-04-27 06:30 UTC by ro90

2021-05-17 13:25 UTC, nbennke requested changes

2021-05-17 13:25 UTC, nbennke commented on app/jobs/delete_authors_after_deadline_job.rb
> +    issue.feedback.update(author: nil)
* auf den Collections update_all prüfen und falls keine RuboCop Warnung damit umsetzen
* Supporter hat derzeit keinen Autor -> Mit Robert klären ob der noch fehlt oder entfällt
* `feedback` ist zu pluralisieren -> siehe Issue im Master

2021-05-17 13:25 UTC, nbennke commented on app/jobs/concerns/sql_query.rb
> +  end
Was soll hier genau gefiltert / gesucht werden? Bitte prüfen ob das nicht auch via "select distinct on() ..." angefragt werden kann, um auf die selbst geschriebene Anfrage zu verzichten!

2021-05-17 13:25 UTC, nbennke commented on app/jobs/inform_editorial_staff_on_issues_job.rb
> +  end
Status ist ein Enum und bietet daher auch für jeden Fall einen Scope -> diesen bitte nutzen!

2021-05-17 13:25 UTC, nbennke commented on app/jobs/inform_editorial_staff_on_issues_job.rb
> +  def description_or_photo_not_released
die Methode heiß "...or..." der Filter macht AND -> passt nicht. entweder umbenennen oder Filter korrigieren

2021-05-17 13:25 UTC, nbennke commented on app/jobs/inform_editorial_staff_on_issues_job.rb
> +    SQL
Was soll hier genau gefiltert werden? Das geht m.M. nach auch via `!issue.photos.status_xy.exists?`

2021-05-17 20:54 UTC, nbennke requested changes

2021-05-17 20:54 UTC, nbennke commented on app/jobs/unconfirmed_issues_deletion_job.rb
> +    Issue.where(iat[:status].eq('pending').and(iat[:created_at].lt(time)))
```suggestion
    Issue.status_pending.where iat[:created_at].lt(time)
```

2021-05-17 20:54 UTC, nbennke commented on app/models/issue/scope.rb
> +class Issue
Achtung hier gibt es ggf Überschneidung mit #22

2021-05-17 20:54 UTC, nbennke commented on app/views/issue_mailer/_not_supported.text.erb
> +<% end -%>
Hier fehlt Content?!?

2021-05-17 20:54 UTC, nbennke commented on app/models/jobs.rb
> +class Jobs
Bitte in `JobsSettings` umbenennen, um den Inhalt besser auszudrücken.

2021-05-17 20:54 UTC, nbennke commented on app/models/jobs.rb
> +    .with_indifferent_access.each do |context, options|
```suggestion
  (@config ||= Config.for(:jobs)).each do |context, options|
```

2021-05-17 20:54 UTC, nbennke commented on app/models/abuse_report.rb
> +  after_create :send_confirmation
Zusammen mit `set_confirmation` inkl. zugehöriger Callbackdefinition und `send_confirmation` in ein `ConfirmationCallbacks` Concern auslagern und an allen Stellen verwenden / inkludieren.

2021-05-17 20:54 UTC, nbennke commented on app/views/confirmation_mailer/abuse.text.erb
> +Ihr <%= Settings::Instance.name %>-Team
Mailer können auch eigene Layouts haben -> für ConfirmationMailer bitte ein Text-Layout erstellen in dem nur die Zeile 3 mit der Url der individuelle Content via `yield` eingefügt wird.

2021-05-17 20:54 UTC, nbennke commented on app/views/confirmation_mailer/issue.text.erb
> +Mit Ihrer Bestätigung erklären Sie sich damit einverstanden, dass wir die von Ihnen im Rahmen der Meldung selbständig gemachten Angaben (Beschreibung) sowie insbesondere das Foto redaktionell bearbei
Diesen Block via `content_for :additional_infos` an das Layout übergeben

2021-05-17 20:54 UTC, nbennke commented on app/views/confirmation_mailer/issue.text.erb
> +Sehr geehrte(r) Nutzer/-in von <%= Settings::Instance.name %>,
ConfirmationMailer-Layout nutzen

2021-05-17 20:54 UTC, nbennke commented on app/views/confirmation_mailer/photo.text.erb
> +Sehr geehrte(r) Nutzer/-in von <%= Settings::Instance.name %>,
ConfirmationMailer-Layout nutzen

2021-05-17 20:54 UTC, nbennke commented on app/views/confirmation_mailer/supporter.text.erb
> +Sehr geehrte(r) Nutzer/-in von <%= Settings::Instance.name %>,
ConfirmationMailer-Layout nutzen

2021-05-17 20:54 UTC, nbennke commented on app/views/issue_mailer/_in_process.text.erb
> +
```suggestion
```

2021-05-17 20:54 UTC, nbennke commented on app/views/issue_mailer/_in_process_no_status_note.text.erb
> +
```suggestion
```

2021-05-17 20:54 UTC, nbennke commented on app/views/issue_mailer/_not_solvable_no_status_note.text.erb
> +
```suggestion
```

2021-05-17 20:54 UTC, nbennke commented on app/views/issue_mailer/_open_not_accepted.text.erb
> +
```suggestion
```

2021-05-17 20:54 UTC, nbennke commented on app/views/issue_mailer/_unsupported_ideas.text.erb
> +
```suggestion
```

2021-05-26 08:28 UTC, nbennke approved these changes

2021-05-26 08:29 UTC, nbennke requested changes
Bitte noch den Punkt mit den redaktionellen Banachrichtigungen prüfen und ergänzen.

2021-05-26 17:55 UTC, nbennke requested changes
Bitte die Anpassungen und Templatedaten aus Redmine #2747 (PR #34) für die Integration der externen Kartenlinks beim Merge berücksichtigen. Dabei sind jedoch nicht alle Werte aus #34 im Template korrekt!

2021-05-28 09:41 UTC, nbennke requested changes
* https://github.com/bfpi/klarschiff-backoffice/pull/14/files#r633770054
* https://github.com/bfpi/klarschiff-backoffice/pull/14/files#r633858567

2021-05-28 11:12 UTC, ro90 commented
>     * https://github.com/bfpi/klarschiff-backoffice/pull/14/files#r633770054
> 
>     * https://github.com/bfpi/klarschiff-backoffice/pull/14/files#r633858567

Die Logik wurde angepasst

2021-05-28 11:20 UTC, nbennke approved these changes

2021-05-28 11:21 UTC, merged