Validierung von Meldungspositionen. Schließen von Meldungen außerhalb des Zuständigkeitsbereichs
bfpi/klarschiff-backoffice pull request #160
Opened 2022-03-01 08:56 UTC by ro90

…bar (Bearbeiter). Schließen von Meldungen außerhalb des Zuständigkeitsbereiches

2022-04-04 11:50 UTC, nbennke requested changes
Durch die Anpassungen aus #189 müssen auch die Code-Verschiebungen in das `Setters` Concern aktualisiert und nach einem Rebase geprüft werden.

2022-05-05 06:43 UTC, ro3t commented on app/models/issue/callbacks.rb
> +    end
Die Districts am User sind leider nicht ausreichend. Ein District ist kein Pflichtfeld und würde lediglich die Zuständigkeit für Amt/Kreis/Instanz noch weiter einschränken. Zu Prüfen ist hier auf die Regionale ausdehnung der zugewiesenen Gruppen des Nutzers.

2022-05-05 06:44 UTC, ro3t requested changes

2022-05-05 06:44 UTC, ro3t commented on app/models/issue/callbacks.rb
> +    end
Die Districts am User sind leider nicht ausreichend. Ein District ist kein Pflichtfeld und würde lediglich die Zuständigkeit für Amt/Kreis/Instanz noch weiter einschränken. Zu Prüfen ist hier auf die Regionale ausdehnung der zugewiesenen Gruppen des Nutzers.

2022-06-15 11:40 UTC, nbennke approved these changes

2022-06-15 11:40 UTC, ro3t approved these changes

2022-06-15 11:42 UTC, merged