Redmine #2702: Suche, Auflistung und Export von Meldungen
bfpi/klarschiff-backoffice pull request #22
Opened 2021-05-10 05:35 UTC by ro90

2021-05-10 12:29 UTC, nbennke requested changes
Der gesamte Branch sollte einmal zusammengefasst und auf den aktuellen Mast rebased werden. In der aktuellen Fassung scheint hier ziemlich viel parallel g/ doppelt gelaufen zu sein!

2021-05-17 11:38 UTC, nbennke requested changes
Ich habe noch einige Anpassungen ergänzt. 

Es gibt noch ein Problem mit dem erweiterten Filter. Die Selektion der Stadtteile enthält die Multipoligone als value, statt der Stadteil-ID. Zum einen führt das zu einer zu langen URL bei der Suchanfrage und andererseits muss mit der aktuellen Umsetzung der Poligonwert aus dem Nutzerrequest gegen die DB gesendet werden. Gefahr von SQL-Injektion!
Das bitte so umstellen das zu den Namen der Stadtteile deren IDs als Identifikator in den Options stehen und darüber die Filterung erfolgt.

Rest sah soweit dann gut aus.

2021-05-17 21:25 UTC, nbennke requested changes

2021-05-17 21:25 UTC, nbennke commented on app/models/issue_filter.rb
> +    @collection = @collection.where('ST_CONTAINS(?::geometry, position::geometry)', "SRID=4326;#{district.area}")
Ist die Angabe der SRID tatsächlich notwendig?
Schreibweise der Funktion gemäß Doku: ST_Contains

2021-05-18 04:24 UTC, ro90 commented on app/models/issue_filter.rb
> +    @collection = @collection.where('ST_CONTAINS(?::geometry, position::geometry)', "SRID=4326;#{district.area}")
Ja, die Werte aus der position-Spalte haben alle die SRID=4326, die SRID für district.model = 0 ist. Wenn ich die SRID nihct angebe, führt es zu folgendem Datenbankfehler: "Operation on mixed SRID geometries"

2021-05-19 06:20 UTC, nbennke requested changes

2021-05-19 06:20 UTC, nbennke commented on app/models/issue_filter.rb
> +    @collection = @collection.where('ST_Contains(?::geometry, position::geometry)', "SRID=4326;#{district.area}")
Nach rebase auf Master sollte die SRID-Angabe nun nicht mehr nötig  sein!

2021-05-20 11:38 UTC, nbennke requested changes
* Die Einschränkung / Suche nach Stadtteilen liefert bisher keine Treffer
* Die Stadtteile in der erweiterten Suche bitte alphabetisch sortieren, der "Alle Ortsteile" Eintrag soll dabei an erster Stelle bleiben
* Es scheint noch ein Problem mit den JS Events zu geben. Bei Auswahl von Werten aus den Lookups / Selects werden bei mir immer gleich 2 identische Requests gegen /data_dependencies gesendet

2021-05-21 05:10 UTC, ro90 commented
>     * Die Einschränkung / Suche nach Stadtteilen liefert bisher keine Treffer
Ich konnte den Fehler nicht reproduzieren. Selbst eigens angelegte Meldungen werden korrekt gefiltert.

2021-05-25 13:10 UTC, merged