Redmine #2856: Empfänger von Lob, Hinweisen und/oder Kritik nach neuer Logik identifizieren
bfpi/klarschiff-backoffice pull request #29
Opened 2021-05-21 11:24 UTC by ro90

2021-05-25 19:14 UTC, nbennke requested changes
Wie wurde auf den folgenden Punkt eingegangen? Das konnte ich nicht direkt erkennen:
* (*) Meldung delegiert? Dann Delegationsgruppe-/rolle verwenden!

2021-05-25 19:14 UTC, nbennke commented on app/models/issue.rb
> +    all_log_entries.where(table: 'issue').order(created_at: :desc).first
```suggestion
    all_log_entries.order(created_at: :desc).find_by table: 'issue'
```

2021-05-25 19:20 UTC, nbennke requested changes
Bullet sagt:
```
GET /issues/51099/edit?tab=log_entry
USE eager loading detected
  LogEntry => [:user]
  Add to your query: .includes([:user])
Call stack
  app/views/issues/_tab_log_entry.html.erb:16:in `block in _app_views_issues__tab_log_entry_html_erb__3799981296860853360_124920'
  app/views/issues/_tab_log_entry.html.erb:13:in `_app_views_issues__tab_log_entry_html_erb__3799981296860853360_124920'
  app/views/issues/_form.html.erb:22:in `_app_views_issues__form_html_erb___2282032279674481596_122520'
  app/views/issues/_edit.html.erb:10:in `block in _app_views_issues__edit_html_erb__272682528663988298_122500'
  app/views/issues/_edit.html.erb:3:in `_app_views_issues__edit_html_erb__272682528663988298_122500'
  app/views/application/edit.js.erb:1:in `_app_views_application_edit_js_erb__2951135076176883958_122480'

GET /issues/51099/edit?tab=log_entry
USE eager loading detected
  LogEntry => [:auth_code]
  Add to your query: .includes([:auth_code])
Call stack
  app/views/issues/_tab_log_entry.html.erb:16:in `block in _app_views_issues__tab_log_entry_html_erb__3799981296860853360_124920'
  app/views/issues/_tab_log_entry.html.erb:13:in `_app_views_issues__tab_log_entry_html_erb__3799981296860853360_124920'
  app/views/issues/_form.html.erb:22:in `_app_views_issues__form_html_erb___2282032279674481596_122520'
  app/views/issues/_edit.html.erb:10:in `block in _app_views_issues__edit_html_erb__272682528663988298_122500'
  app/views/issues/_edit.html.erb:3:in `_app_views_issues__edit_html_erb__272682528663988298_122500'
  app/views/application/edit.js.erb:1:in `_app_views_application_edit_js_erb__2951135076176883958_122480'
```

2021-05-26 05:32 UTC, ro90 commented
> Wie wurde auf den folgenden Punkt eingegangen? Das konnte ich nicht direkt erkennen:
> 
>     * (*) Meldung delegiert? Dann Delegationsgruppe-/rolle verwenden!
In der identify_recipients-Methode (app/models/feedback.rb:26) wird die entsprechende Gruppe aus der Delegation oder der Zuweisung der Meldung bestimmt.

2021-05-26 11:35 UTC, nbennke approved these changes

2021-05-26 11:40 UTC, merged