Ticket #2711: Nutzer- bzw. Gruppen-/Rollenrechte
bfpi/klarschiff-backoffice pull request #35
Opened 2021-05-27 12:34 UTC by ro3t

2021-05-27 12:51 UTC, nbennke approved these changes

2021-05-31 07:17 UTC, nbennke requested changes

2021-05-31 07:17 UTC, nbennke commented on app/controllers/groups_controller.rb
> +    @group = Group.new(type: InstanceGroup)
```suggestion
    @group = InstanceGroup.new
```
Geht das nicht auch? Oder kollidiert das mit den `becomes(Group)` Anweisungen in den Views?

2021-05-31 07:17 UTC, nbennke commented on app/helpers/groups_helper.rb
> +end
```suggestion
  def references(group)
    return Authority.authorized if group.is_a? AuthorityGroup
    return County.authorized if group.is_a? CountyGroup
    Instance.all
  end
end
```
Dann muss der Aufruf aber auch angepasst werden

2021-05-31 07:17 UTC, nbennke commented on app/models/county.rb
> +      }.flatten.map(&:reference_id)
sieht etwas kompliziert aus. eigentlich dürften am County nur CountyGroups verlinkt sein...

2021-05-31 07:17 UTC, nbennke commented on app/models/group.rb
> +      where id: user.groups.map { |gr| Group.where(type: gr.type, reference_id: gr.reference_id) }.flatten.map(&:id)
Was soll gefiltert werden? geht das nicht auch ohne map und flatten?

2021-05-31 07:17 UTC, nbennke commented on app/models/group.rb
> +    elsif user&.role_regional_admin?
```suggestion
    return active if user&.role_admin?
    if user&.role_regional_admin?
```

2021-05-31 07:17 UTC, nbennke commented on app/models/issue/scopes.rb
> +        authorized_group_ids = authorized_groups(user)
```suggestion
        authorized_group_ids = authorized_group_ids(user)
```

2021-05-31 07:17 UTC, nbennke commented on app/models/issue/scopes.rb
> +      def authorized_groups(user = Current.user)
```suggestion
      def authorized_group_ids(user = Current.user)
```

2021-05-31 07:17 UTC, nbennke commented on app/models/issue/scopes.rb
> +        return user.groups.map(&:id) unless user&.role_regional_admin?
```suggestion
        return user.group_ids unless user&.role_regional_admin?
```

2021-05-31 07:17 UTC, nbennke commented on app/models/issue/scopes.rb
> +        user.groups.map { |gr| Group.where(type: gr.type, reference_id: gr.reference_id) }.flatten.map(&:id)
besser ohne map und flatten machen

2021-05-31 07:17 UTC, nbennke commented on db/migrate/20210525123743_drop_community_table.rb
> +  def change; end
Hier fehlt das drop!

2021-05-31 07:25 UTC, ro3t commented on app/helpers/groups_helper.rb
> +    Group.distinct(:type).uniq.reverse
die verschiedenen in der db vorhandenen Types abfragen

2021-05-31 07:44 UTC, ro3t commented on app/helpers/groups_helper.rb
> +end
es ist nicht immer ein Gruppen-Objekt vorhanden. Beim rendern des partials im DataDependencies controller habe ich keine Gruppe von der ich das abfragen kann.

2021-05-31 08:10 UTC, nbennke commented on app/helpers/groups_helper.rb
> +    Group.distinct(:type).uniq.reverse
Aber das distinct(:types) bewirkt nichts...

2021-05-31 08:11 UTC, ro3t commented on app/helpers/groups_helper.rb
> +    Group.distinct(:type).uniq.reverse
Deswegen habe ich das lokal auch schon geändert. ;-)

2021-05-31 08:12 UTC, nbennke commented on app/helpers/groups_helper.rb
> +end
Dann bleibt es so

2021-06-01 13:19 UTC, nbennke requested changes
Code sieht soweit ganz gut aus, bis auf der Hinweis zur Migration. Test der Funktion steht noch aus.

Bitte einmal den aktuellen Master in diesen Branch mergen oder auf den Master rebasen um die Konflikte zu beheben.

2021-06-01 13:19 UTC, nbennke commented on db/migrate/20210525123743_drop_community_table.rb
> +    raise ActiveRecord::IrreversibleMigration
warum das explizite raise? was spricht dagegen das ursprüngliche create table zu ergänzen / auszuführen? Die Daten sind zwar nach der Migration weg, aber es gibt dann keinen Fehler falls man die Migration zurückrollen möchte....

2021-06-01 13:19 UTC, nbennke commented on db/migrate/20210525123743_drop_community_table.rb
> +    raise ActiveRecord::IrreversibleMigration
```
create_table "community", force: :cascade do |t|
  t.text "regional_key"
  t.text "name"
  t.geometry "area", limit: {:srid=>4326, :type=>"multi_polygon"}
  t.bigint "authority_id", null: false
  t.datetime "created_at", precision: 6, null: false
  t.datetime "updated_at", precision: 6, null: false
  t.index ["authority_id"], name: "index_community_on_authority_id"
end
```

2021-06-02 11:35 UTC, merged