Ticket #63: Zuständigkeiten - überflüssige Buttons
bfpi/klarschiff-backoffice pull request #365
Opened 2023-12-11 07:03 UTC by ro90

https://intern.bfpi.de/trac-klarschiff/ticket/63

2023-12-12 08:43 UTC, ro3t requested changes

2023-12-12 08:43 UTC, ro3t commented on app/helpers/responsibilities_helper.rb
> +
Wo wird diese Methode verwendet?

2024-03-27 08:06 UTC, nbennke approved these changes

2024-03-27 08:08 UTC, ro3t approved these changes

2024-03-27 08:09 UTC, merged