Redmine #2751: virtuelle Externe
bfpi/klarschiff-backoffice pull request #38
Opened 2021-06-01 05:45 UTC by ro90

2021-06-01 13:06 UTC, nbennke requested changes
* Bitte einmal auf den Master rebasen / den Master mergen und Mergekonflikte beheben.
* Wenn ein Link zu einer Meldung / Delegation mit einem ungültigen AuthCode aufgerufen wird gibt es derzeit einen Fehler:
```
#<UserAuthorization::NotAuthorized:  is not authorized to edit_delegation.>
app/controllers/concerns/authorization.rb:70:in `check_auth'
 app/controllers/delegations_controller.rb:17:in `show'
```
* In der Webseite steht für den Nutzer: Es ist ein interner Fehler aufgetreten. is not authorized to edit_delegation. 
* Das Abfangen über UserAuthorization::NotAuthorized ist grundsätzlich okay, jedoch die Fehlermeldung für den Endnutzer sollte in der Form "Sie haben nicht die nötigen Rechte für diese Aktion!" erfolgen.
* Weiterhin kann der so abgewiesene Nutzer anschließend alle Meldungen sehen. Das muss verhindert werden. Ohne validen AuthCOde = KEIN Zugriff, auf nichts außer Impressum und Datenschutz

2021-06-02 05:42 UTC, nbennke commented
Mit PR #41 habe ich bereits ein Commit (5587f29) ergänzt, das die Behandlung der Nicht-Authorisierung ergänzt.

2021-06-02 13:24 UTC, nbennke requested changes
* Das Menü muss noch bei AuthCode eingeschränkt werden
* Interne Kommentare (Comments) brauchen die gleiche Behandlung bezüglich user und auth_code wie log_entry, sonst können keine Kommentare ergänzt werden
```
  ↳ app/controllers/comments_controller.rb:10:in `create'
#<ArgumentError: comparison of Integer with String failed>
app/models/user.rb:52:in `<'
app/models/user.rb:52:in `role_permissions'
```

2021-06-03 07:09 UTC, nbennke commented
Bitte bei der Bearbeitung der Rückmeldungen auch die Konflikte mit dem aktuellen Master beheben: https://github.com/bfpi/klarschiff-backoffice/pull/38/conflicts

2021-06-04 06:25 UTC, nbennke commented
Prüfen Linktext Delegationen -> Meldungen für Externe

2021-06-07 22:15 UTC, nbennke requested changes

2021-06-07 22:15 UTC, nbennke commented on app/controllers/abuse_reports_controller.rb
> +    @abuse_report = AbuseReport.create!(permitted_params.merge(author: Current.user.author))
Was ist user.author? Meintest du Current.author? Author wird doch immer mit der email belegt, das sollte doch dann user.email bleiben...oder nicht? Was ist der Grund für diese Änderung?

2021-06-07 22:15 UTC, nbennke commented on app/controllers/comments_controller.rb
> +      permitted_params.merge(user: Current.user, auth_code: Current.user&.auth_code)
geht das mit Current.user wenn der user wegen des auth_code  nur initialisiert ist und nicht gespeichert werden soll? Beim LogEntry wird hierfür explizit die user_id  verwendet!

2021-06-07 22:15 UTC, nbennke commented on app/models/feedback.rb
> +    group.recipient
ohne die unterschiedliche Prüfung (wie vorher) liefern beide Zeilen das selbe... dann kann die erste weg. Aber ist das so gewollt?

2021-06-07 22:15 UTC, nbennke commented on app/models/group.rb
> +  def recipient
Da es sich bei diesem "recipient" nur um den Feedback recipient handelt sollte die Methode auch so heißen -> feedback_recipient

2021-06-07 22:15 UTC, nbennke commented on app/models/user.rb
> +  def author
Jetzt verstehe ich die Änderung von oben... aber den Author an dem user zu definieren ist etwas quer. Dann besser als Current.author mit der Logik über Current.user.auth_code ...

2021-06-08 05:07 UTC, ro90 commented on app/controllers/comments_controller.rb
> +      permitted_params.merge(user: Current.user, auth_code: Current.user&.auth_code)
Sowohl für comment, alsmauch für log_entry geht das mit Current.user

2021-06-08 10:19 UTC, ro3t requested changes
- das Bearbeiten einer Meldung als interner Nutzer (nicht Admin) klappt nicht mehr
- es sollte ebenfalls Berücksichtigt werden, dass es eine interne Gruppe ohne Benutzer geben könnte die direkt Zuständig ist (nicht nur die deligierten). Sonst könnten wir die Rathaustür nicht Informieren. Diese müssen dann alle Informationen bearbeiten dürfen
- nachdem die Meldung vom virtuellen Externen zurückgewiesen wurde sollte dieser keine Berechtigungen mehr zum bearbeiten haben.

2021-06-08 11:38 UTC, ro3t commented
- für die Zuständige Gruppen muss ebenfalls ein auth_code generiert und via Mail an die Zuständige Interne Gruppe verschickt werden
- der Job sollte dann auch anders benannt werden. InformVirtualUserJob
- für abgeschlossene Meldungen braucht kein AuthCode mehr erzeugt und verschickt werden. Nur für offene Meldungen
- Aktuell lässt sich keine Meldung mehr bearbeiten: Sie haben nicht die nötigen Rechte für diese Aktion! 
- In der URL sollte nicht die Issue-ID stehen. Diese sollte nur durch den auth_code identifiziert werden können

2021-06-10 13:10 UTC, merged