Ticket 2703
bfpi/klarschiff-backoffice pull request #8
Opened 2021-04-13 07:08 UTC by ro90

2021-04-26 06:40 UTC, ro3t requested changes
- Bitte noch ein Rebase auf den Master durchführen und eventuelle Meldungen von bin/check beheben.
- Auf der Karte wird nichts angezeigt. In der Console kommen JS-Fehler.
- Das erzeugte Excel-Dokument bitte mit etwas Layout entsprechend dem Altsystem versehen (Spaltenbreiten, Überschriftszeile).

2021-04-28 05:20 UTC, ro90 commented
>     * Auf der Karte wird nichts angezeigt. In der Console kommen JS-Fehler.

Dieser Fehler konnte nicht reporduziert werden. Der Rest wurde umgesetzt

2021-05-05 07:56 UTC, ro3t reviewed
- Leider doch noch JS-Fehler bei der Karte. Bitte noch mal mit dem DB-Dump prüfen.
- Bullet sagt:
```
GET /delegations
USE eager loading detected
  Issue => [:category]
  Add to your query: .includes([:category])
Call stack
 app/models/issue.rb:38:in `kind'
 app/views/delegations/index.html.erb:32:in `block in _app_views_delegations_index_html_erb__546338318744574089_30160'
 app/views/delegations/index.html.erb:29:in `_app_views_delegations_index_html_erb__546338318744574089_30160'
```

2021-05-05 07:56 UTC, ro3t commented on app/views/delegations/index.html.erb
> +            <%= Issue.human_enum_name(:status, issue.status) %>
Das Icon mit der Bezeichnung als title reicht.
```suggestion
          <%= image_tag issue.list_icon, class: "status-icon #{issue.status}",
                                         title: Issue.human_enum_name(:status, issue.status) %>
```

2021-05-05 07:56 UTC, ro3t commented on app/views/delegations/index.html.erb
> +          <td><%= MainCategory.human_enum_name(:kind, issue.kind) %></td>
Der Typ kann als eigene Spalte entfallen. An diese Stelle bitte die Status-Spalte verschieben.

2021-05-06 05:08 UTC, merged